### ISSUE TITLE
请问  Cannot access 'java.util.List' which is a supertype of 'org.gradle.api.artifacts.dsl.RepositoryHandler'. 该怎么处理？

### ISSUE THREAD

**Issue by jingzz1** [PengHaiZhuo/BuildSrcDemo#1]
![image](https://user-images.githubusercontent.com/29534171/126729769-e0d6152b-443f-44e8-9c24-678874bdfb07.png)

build.gradle.kts报异常：
Cannot access 'java.lang.Object' which is a supertype of 'org.gradle.plugin.use.PluginDependenciesSpec'. Check your module classpath for missing or conflicting dependencies

**Comment by PengHaiZhuo** [comment]
嗨，抱歉这么久才回复。
我认为这是jdk设置造成的，请确保module里有指定目标版本，像这样
```
compileOptions {
   sourceCompatibility = JavaVersion.VERSION_1_8
   targetCompatibility = JavaVersion.VERSION_1_8
}
kotlinOptions {
   jvmTarget = "1.8"
}
```
然后检查File->Build,Execution,Deployment##gradle jdk版本 是否与IDE的jdk保持一致。最后重启IDE。
